name: Publish Package

on:
  push:
    branches:
      - feat/code-artifact-v2

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env: 
      PR_NUMBER: ${{ github.event.number }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
      # Change Account to Ops Account
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2 # change to appropriate region
          role-to-assume: arn:aws:iam::794844780483:role/codeartifact-githubactions-role
          role-session-name: RepoPublishPackage
          role-duration-seconds: 900

      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install bump2version
        run: |
          pip install bumpversion

      - name: Bump Version # run the run.py to get the latest data
        run: |
          bumpversion --current-version 1.1.9 major setup.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped version to ${{ env.CURRENT_VERSION }}

      - name: Install Twine
        run: |
          pip install wheel twine

      - name: Build Package
        run: |
          python setup.py sdist

      - name: Publish Package
        run: |
          aws codeartifact login --tool twine --repository manual-dbt-spark --domain manual-dbt-spark --domain-owner 794844780483 &&
          twine upload --repository codeartifact dist/* --verbose
